// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using retailApp.Data;

#nullable disable

namespace retailApp.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("retailApp.Model.DisqualificationReason", b =>
                {
                    b.Property<int>("DisqualificationReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisqualificationReasonId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisqualificationReasonId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductId1")
                        .IsUnique()
                        .HasFilter("[ProductId1] IS NOT NULL");

                    b.ToTable("DisqualificationReasons");
                });

            modelBuilder.Entity("retailApp.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("DisqualificationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsQualified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("retailApp.Model.DisqualificationReason", b =>
                {
                    b.HasOne("retailApp.Model.Product", "Product")
                        .WithOne()
                        .HasForeignKey("retailApp.Model.DisqualificationReason", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("retailApp.Model.Product", null)
                        .WithOne("DisqualificationReasonEntity")
                        .HasForeignKey("retailApp.Model.DisqualificationReason", "ProductId1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("retailApp.Model.Product", b =>
                {
                    b.Navigation("DisqualificationReasonEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
